# Generated by Django 2.2.7 on 2020-08-30 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.AutoField(primary_key=True, serialize=False)),
                ('rateClient', models.IntegerField(blank=True, null=True)),
                ('userClient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('idCompany', models.AutoField(primary_key=True, serialize=False)),
                ('nameCompany', models.CharField(blank=True, max_length=45, null=True)),
                ('typeCompany', models.CharField(blank=True, max_length=45, null=True)),
                ('addressCompany', models.CharField(blank=True, max_length=45, null=True)),
                ('webpageCompany', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('idDriver', models.AutoField(primary_key=True, serialize=False)),
                ('rateDriver', models.IntegerField(blank=True, null=True)),
                ('userDriver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('idFare', models.AutoField(primary_key=True, serialize=False)),
                ('maxFare', models.IntegerField(blank=True, null=True)),
                ('priceFare', models.FloatField(blank=True, null=True)),
                ('idCompanyFare', models.ForeignKey(db_column='idCompany', on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.Company')),
            ],
            options={
                'db_table': 'fare',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('idLocation', models.AutoField(primary_key=True, serialize=False)),
                ('latitudeLocation', models.CharField(blank=True, max_length=20, null=True)),
                ('longitudeLocation', models.CharField(blank=True, max_length=20, null=True)),
                ('nameLocation', models.CharField(blank=True, max_length=200, null=True)),
                ('tokenLocation', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('idPayment', models.AutoField(primary_key=True, serialize=False)),
                ('typePayment', models.CharField(blank=True, max_length=45, null=True)),
                ('amountPayment', models.FloatField(blank=True, null=True)),
                ('driverneedPayment', models.FloatField(blank=True, null=True)),
                ('chargeamountPayment', models.FloatField(blank=True, null=True)),
                ('totalPayment', models.FloatField(blank=True, null=True)),
                ('datePayment', models.DateTimeField(blank=True, null=True)),
                ('tokenPayment', models.CharField(blank=True, max_length=200, null=True)),
                ('idFarePayment', models.ForeignKey(db_column='idFare', on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.Fare')),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('idTypeService', models.AutoField(primary_key=True, serialize=False)),
                ('nameTypeService', models.CharField(blank=True, max_length=45, null=True)),
                ('descriptionTypeService', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'typeService',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('idVehicle', models.AutoField(primary_key=True, serialize=False)),
                ('brandVehicle', models.CharField(blank=True, max_length=45, null=True)),
                ('typeVehicle', models.CharField(blank=True, max_length=45, null=True)),
                ('modelVehicle', models.CharField(blank=True, max_length=45, null=True)),
                ('colorVehicle', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('idService', models.AutoField(primary_key=True, serialize=False)),
                ('driverScore', models.IntegerField(blank=True, null=True)),
                ('clientScore', models.IntegerField(blank=True, null=True)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('isReservationService', models.BooleanField(blank=True, null=True)),
                ('stateService', models.IntegerField(blank=True, null=True)),
                ('endidLocation', models.ForeignKey(db_column='idLocation', on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.Location')),
                ('idClientService', models.ForeignKey(db_column='idClient', on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.Client')),
                ('idDriverService', models.ForeignKey(db_column='idDriver', on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.Driver')),
                ('idPaymentService', models.ForeignKey(db_column='idPayment', on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.Payment')),
                ('idTypeService', models.ForeignKey(db_column='idTypeService', on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.TypeService')),
            ],
            options={
                'db_table': 'service',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='fare',
            name='idTypeServiceFare',
            field=models.ForeignKey(db_column='idTypeService', on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.TypeService'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicleDriver',
            field=models.ForeignKey(db_column='idVehicle', on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.Vehicle'),
        ),
    ]
