# Generated by Django 2.2.7 on 2020-11-24 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVehicular', '0003_auto_20201105_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicleDriver',
        ),
        migrations.AddField(
            model_name='driver',
            name='activeDriver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='addressDriver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='birthdateDriver',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='ciDriver',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='cipictureDriver',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='companyDriver',
            field=models.ForeignKey(db_column='idCompany', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.Company'),
        ),
        migrations.AddField(
            model_name='driver',
            name='emailDriver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='licenceDriver',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='lnameDriver',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='nameDriver',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='phoneDriver',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='sexDriver',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='stateDriver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pictureVehicle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plateVehicle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plpictureVehicle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registrationVehicle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='typeServiceVehicle',
            field=models.ForeignKey(db_column='idTypeService', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.TypeService'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='userVehicle',
            field=models.ForeignKey(db_column='idDriver', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.Driver'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='yearVehicle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='userDriver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='driver',
            table='drive',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('idPolice', models.AutoField(primary_key=True, serialize=False)),
                ('descriptionPolice', models.TextField(blank=True, null=True)),
                ('typePolice', models.CharField(blank=True, max_length=200, null=True)),
                ('companyPolice', models.ForeignKey(db_column='idCompany', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.Company')),
            ],
            options={
                'db_table': 'police',
                'managed': True,
            },
        ),
    ]
