# Generated by Django 2.2.7 on 2020-12-11 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVehicular', '0004_auto_20201123_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='idDriverService',
            field=models.ForeignKey(blank=True, db_column='idDriver', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appVehicular.Driver'),
        ),
    ]
