# Generated by Django 2.2.7 on 2020-12-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVehicular', '0005_auto_20201211_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='stateService',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
