# Generated by Django 2.2.7 on 2020-12-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVehicular', '0006_auto_20201211_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='stateService',
            field=models.IntegerField(choices=[('0', 'UNASSIGNED'), ('1', 'ASSIGNED')], default=0),
        ),
    ]
