# Generated by Django 2.2.7 on 2020-12-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVehicular', '0008_auto_20201211_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='stateService',
            field=models.IntegerField(choices=[(0, 'UNASSIGNED'), (1, 'ASSIGNED'), (2, 'EN CURSO'), (3, 'FINALIZADO')], default=0),
        ),
    ]
